### PR TITLE
MQTT Router Improved Queue

### LINKED ISSUE #1: Separate handler logics based on the retain allowance
## Summary

We need to implement a way to handle the logics for both `allowedRetain: true` and `allowedRetain: false` as separately. We may also need to configure the route handler function in this implementation as well.

### LINKED ISSUE #2: Flexible routing
## Summary

We need to implement the functionality to unsubscribe from certain routes declared in the routes array and add other subscriptions and routes after starting the router. Also we need to consider the publishers as well.

### LINKED ISSUE #3: MQTT Publish Queue
## Requirements
- Need to implement a queue for message publication.
- MQTT class (MQTT router + this implementation) should frequently check the queue and publish the message in the queue.

### PR DESCRIPTION
**Pull request by luk3Sky**
### Changelog

- Added cron
- Queue scheduler support
- Added test client support
- Publish queue made to be handled after handling initial subscribers
- Included `addRoute` and `removeRoute` for the routes
- Fixed issues #1 #2 #3

### CODE REVIEW

**Review by NuwanJ — COMMENTED** [review]
What happens if there two or more messages in the queue and remove a message from Queue using the *remove(topic: string)* function? What are the use cases for that function ?

**Review by NuwanJ — COMMENTED** [review]
In router.ts, it seems to be the order of if conditions must be changed to allow the second one to happen. @luk3Sky please check.

```
} else if (packet.retain && this._routes[i].allowRetained) {
                            // Older/Retained messages
                            // Note: Accept and handle 'retained true logic' only if both the packet is retained and the route allows retained packets
                            this.callHandler(topic, msg, this._routes[i]);
                        } else if (
                            packet.retain &&
                            !this._routes[i].allowRetained &&
                            this._routes[i].fallbackRetainHandler !== undefined
                        ) {
                            // Older/Retained messages
                            // Note: Accept and handle 'retained false logic' if both the packet is retained and the route doesn't allow retained packets
                            this.callFallback(topic, msg, this._routes[i]);
                        }
```

**Comment by luk3Sky** [comment]
> What happens if there two or more messages in the queue and remove a message from Queue using the _remove(topic: string)_ function? What are the use cases for that function ?

This will come in handy when a custom application with a higher scheduler interval and a higher number of messages in the queue which are to be published but, a newer message could be replaced rather than the older message which is already in the queue. The `Queue` class is independent from the router and can be used for any use case. However, this might not be useful for our particular use cases.

**Comment by luk3Sky** [comment]
> In router.ts, it seems to be the order of if conditions must be changed to allow the second one to happen. @luk3Sky please check.
> 
> ```
> } else if (packet.retain && this._routes[i].allowRetained) {
>                             // Older/Retained messages
>                             // Note: Accept and handle 'retained true logic' only if both the packet is retained and the route allows retained packets
>                             this.callHandler(topic, msg, this._routes[i]);
>                         } else if (
>                             packet.retain &&
>                             !this._routes[i].allowRetained &&
>                             this._routes[i].fallbackRetainHandler !== undefined
>                         ) {
>                             // Older/Retained messages
>                             // Note: Accept and handle 'retained false logic' if both the packet is retained and the route doesn't allow retained packets
>                             this.callFallback(topic, msg, this._routes[i]);
>                         }
> ```

The main constraints are following:
```
/**
 * constraints:
 * all fresh messages will be picked up by handler
 * retained messages that also allows route specific retain property, will be picked up by handler
 * retained messages that not allowed route specific retain property, will be picked up by fallbackRetainHandler if specified, otherswise discarded
 */
```

I think the order is okay, but however I made a mistake on the last if-else clause and I fixed it now.  The last case of this code to `callFallback` method instead of `discard` method. @NuwanJ did you able to run the test client?

**Pull request merged**
